version: '3.8'
services:
  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports: -8000:8000
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=Nickoch96
      - SECRET_KEY=123456HDUDCDHCHDUCDNCNDNCR
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRY_MINUTES=30

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD: Nickoch96
      - POSTGRES_DB: fastapi
    volumes:
      -postgres_data: /var/lib/postgresql/data/

volumes:
  -postgres_data
